### ISSUE TITLE
BDC is showing the state of tomorrow

### ISSUE THREAD

**Issue by john-waitforit** [xeo-labs/xeo#41]
## Expected behaviour: 
- the pink and blue lines should stop at today

## Un-expected behaviour
- the pink and blue lines are going all the way to friday (tomorrow) 
- it also says that we are 15 points late

Screenshot taken on Thursday at 11:44am
![image](https://user-images.githubusercontent.com/19970319/155509454-b794f1b6-e0c3-422d-b7aa-380bf5145ee7.png)

**Comment by oliverbutler** [comment]
Yup I completely agree, I originally wanted to show "Where are we _currently_ up to today".

Maybe for tomorrow morning, in this case "Fri 25/02" we dont draw the lines, but we put two dis-jointed points with no line connecting to yesterday.
